// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: console/v1/manifest.proto

package consolev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectServiceManifest_GetProjectServiceManifest_FullMethodName = "/console.v1.ProjectServiceManifest/GetProjectServiceManifest"
	ProjectServiceManifest_ListProjectServices_FullMethodName       = "/console.v1.ProjectServiceManifest/ListProjectServices"
)

// ProjectServiceManifestClient is the client API for ProjectServiceManifest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectServiceManifestClient interface {
	GetProjectServiceManifest(ctx context.Context, in *GetProjectServiceManifestRequest, opts ...grpc.CallOption) (*GetProjectServiceManifestResponse, error)
	ListProjectServices(ctx context.Context, in *ListProjectServicesRequest, opts ...grpc.CallOption) (*ListProjectServicesResponse, error)
}

type projectServiceManifestClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectServiceManifestClient(cc grpc.ClientConnInterface) ProjectServiceManifestClient {
	return &projectServiceManifestClient{cc}
}

func (c *projectServiceManifestClient) GetProjectServiceManifest(ctx context.Context, in *GetProjectServiceManifestRequest, opts ...grpc.CallOption) (*GetProjectServiceManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectServiceManifestResponse)
	err := c.cc.Invoke(ctx, ProjectServiceManifest_GetProjectServiceManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceManifestClient) ListProjectServices(ctx context.Context, in *ListProjectServicesRequest, opts ...grpc.CallOption) (*ListProjectServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectServicesResponse)
	err := c.cc.Invoke(ctx, ProjectServiceManifest_ListProjectServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceManifestServer is the server API for ProjectServiceManifest service.
// All implementations must embed UnimplementedProjectServiceManifestServer
// for forward compatibility.
type ProjectServiceManifestServer interface {
	GetProjectServiceManifest(context.Context, *GetProjectServiceManifestRequest) (*GetProjectServiceManifestResponse, error)
	ListProjectServices(context.Context, *ListProjectServicesRequest) (*ListProjectServicesResponse, error)
	mustEmbedUnimplementedProjectServiceManifestServer()
}

// UnimplementedProjectServiceManifestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectServiceManifestServer struct{}

func (UnimplementedProjectServiceManifestServer) GetProjectServiceManifest(context.Context, *GetProjectServiceManifestRequest) (*GetProjectServiceManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectServiceManifest not implemented")
}
func (UnimplementedProjectServiceManifestServer) ListProjectServices(context.Context, *ListProjectServicesRequest) (*ListProjectServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProjectServices not implemented")
}
func (UnimplementedProjectServiceManifestServer) mustEmbedUnimplementedProjectServiceManifestServer() {
}
func (UnimplementedProjectServiceManifestServer) testEmbeddedByValue() {}

// UnsafeProjectServiceManifestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectServiceManifestServer will
// result in compilation errors.
type UnsafeProjectServiceManifestServer interface {
	mustEmbedUnimplementedProjectServiceManifestServer()
}

func RegisterProjectServiceManifestServer(s grpc.ServiceRegistrar, srv ProjectServiceManifestServer) {
	// If the following call panics, it indicates UnimplementedProjectServiceManifestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectServiceManifest_ServiceDesc, srv)
}

func _ProjectServiceManifest_GetProjectServiceManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectServiceManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceManifestServer).GetProjectServiceManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectServiceManifest_GetProjectServiceManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceManifestServer).GetProjectServiceManifest(ctx, req.(*GetProjectServiceManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectServiceManifest_ListProjectServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceManifestServer).ListProjectServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectServiceManifest_ListProjectServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceManifestServer).ListProjectServices(ctx, req.(*ListProjectServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectServiceManifest_ServiceDesc is the grpc.ServiceDesc for ProjectServiceManifest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectServiceManifest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "console.v1.ProjectServiceManifest",
	HandlerType: (*ProjectServiceManifestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProjectServiceManifest",
			Handler:    _ProjectServiceManifest_GetProjectServiceManifest_Handler,
		},
		{
			MethodName: "ListProjectServices",
			Handler:    _ProjectServiceManifest_ListProjectServices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "console/v1/manifest.proto",
}
