// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tenant/v1/common.proto

package tenantV1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TenantSuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantSuccessResponse) Reset() {
	*x = TenantSuccessResponse{}
	mi := &file_tenant_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSuccessResponse) ProtoMessage() {}

func (x *TenantSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSuccessResponse.ProtoReflect.Descriptor instead.
func (*TenantSuccessResponse) Descriptor() ([]byte, []int) {
	return file_tenant_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *TenantSuccessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TenantSuccessResponse) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TenantEmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantEmptyRequest) Reset() {
	*x = TenantEmptyRequest{}
	mi := &file_tenant_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantEmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantEmptyRequest) ProtoMessage() {}

func (x *TenantEmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantEmptyRequest.ProtoReflect.Descriptor instead.
func (*TenantEmptyRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_common_proto_rawDescGZIP(), []int{1}
}

var File_tenant_v1_common_proto protoreflect.FileDescriptor

const file_tenant_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x16tenant/v1/common.proto\x12\ttenant.v1\x1a\x1bbuf/validate/validate.proto\x1a\x19google/protobuf/any.proto\"j\n" +
	"\x15TenantSuccessResponse\x12!\n" +
	"\amessage\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\amessage\x12.\n" +
	"\apayload\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\apayload\"\x14\n" +
	"\x12TenantEmptyRequestB7Z5github.com/vyolayer/vyolayer/proto/tenant/v1;tenantV1b\x06proto3"

var (
	file_tenant_v1_common_proto_rawDescOnce sync.Once
	file_tenant_v1_common_proto_rawDescData []byte
)

func file_tenant_v1_common_proto_rawDescGZIP() []byte {
	file_tenant_v1_common_proto_rawDescOnce.Do(func() {
		file_tenant_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenant_v1_common_proto_rawDesc), len(file_tenant_v1_common_proto_rawDesc)))
	})
	return file_tenant_v1_common_proto_rawDescData
}

var file_tenant_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tenant_v1_common_proto_goTypes = []any{
	(*TenantSuccessResponse)(nil), // 0: tenant.v1.TenantSuccessResponse
	(*TenantEmptyRequest)(nil),    // 1: tenant.v1.TenantEmptyRequest
	(*anypb.Any)(nil),             // 2: google.protobuf.Any
}
var file_tenant_v1_common_proto_depIdxs = []int32{
	2, // 0: tenant.v1.TenantSuccessResponse.payload:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tenant_v1_common_proto_init() }
func file_tenant_v1_common_proto_init() {
	if File_tenant_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_v1_common_proto_rawDesc), len(file_tenant_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tenant_v1_common_proto_goTypes,
		DependencyIndexes: file_tenant_v1_common_proto_depIdxs,
		MessageInfos:      file_tenant_v1_common_proto_msgTypes,
	}.Build()
	File_tenant_v1_common_proto = out.File
	file_tenant_v1_common_proto_goTypes = nil
	file_tenant_v1_common_proto_depIdxs = nil
}
