// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tenant/v1/organization_invitation.proto

package tenantV1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------
// Invitation Requests
// --------------------
type CreateInvitationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	RoleIds        []string               `protobuf:"bytes,3,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateInvitationRequest) Reset() {
	*x = CreateInvitationRequest{}
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvitationRequest) ProtoMessage() {}

func (x *CreateInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvitationRequest.ProtoReflect.Descriptor instead.
func (*CreateInvitationRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_invitation_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInvitationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateInvitationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateInvitationRequest) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type ListInvitationsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	PageSize       int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListInvitationsRequest) Reset() {
	*x = ListInvitationsRequest{}
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitationsRequest) ProtoMessage() {}

func (x *ListInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitationsRequest.ProtoReflect.Descriptor instead.
func (*ListInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_invitation_proto_rawDescGZIP(), []int{1}
}

func (x *ListInvitationsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListInvitationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListInvitationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetPendingInvitationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingInvitationsRequest) Reset() {
	*x = GetPendingInvitationsRequest{}
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingInvitationsRequest) ProtoMessage() {}

func (x *GetPendingInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingInvitationsRequest.ProtoReflect.Descriptor instead.
func (*GetPendingInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_invitation_proto_rawDescGZIP(), []int{2}
}

func (x *GetPendingInvitationsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AcceptInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvitationRequest) Reset() {
	*x = AcceptInvitationRequest{}
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitationRequest) ProtoMessage() {}

func (x *AcceptInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitationRequest.ProtoReflect.Descriptor instead.
func (*AcceptInvitationRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_invitation_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptInvitationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CancelInvitationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InvitationId   string                 `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelInvitationRequest) Reset() {
	*x = CancelInvitationRequest{}
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelInvitationRequest) ProtoMessage() {}

func (x *CancelInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelInvitationRequest.ProtoReflect.Descriptor instead.
func (*CancelInvitationRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_invitation_proto_rawDescGZIP(), []int{4}
}

func (x *CancelInvitationRequest) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

func (x *CancelInvitationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

// --------------------
// Invitation Responses
// --------------------
type OrganizationMemberInvitationResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Invitation    *OrganizationMemberInvitation `protobuf:"bytes,1,opt,name=invitation,proto3" json:"invitation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationMemberInvitationResponse) Reset() {
	*x = OrganizationMemberInvitationResponse{}
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationMemberInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationMemberInvitationResponse) ProtoMessage() {}

func (x *OrganizationMemberInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationMemberInvitationResponse.ProtoReflect.Descriptor instead.
func (*OrganizationMemberInvitationResponse) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_invitation_proto_rawDescGZIP(), []int{5}
}

func (x *OrganizationMemberInvitationResponse) GetInvitation() *OrganizationMemberInvitation {
	if x != nil {
		return x.Invitation
	}
	return nil
}

type ListOrganizationInvitationsResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Invitations   []*OrganizationMemberInvitation `protobuf:"bytes,1,rep,name=invitations,proto3" json:"invitations,omitempty"`
	TotalCount    int32                           `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	NextPageToken string                          `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationInvitationsResponse) Reset() {
	*x = ListOrganizationInvitationsResponse{}
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationInvitationsResponse) ProtoMessage() {}

func (x *ListOrganizationInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationInvitationsResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_invitation_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrganizationInvitationsResponse) GetInvitations() []*OrganizationMemberInvitation {
	if x != nil {
		return x.Invitations
	}
	return nil
}

func (x *ListOrganizationInvitationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListOrganizationInvitationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// --------------------
// Invitation Message
// --------------------
type OrganizationMemberInvitation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	InvitedBy      string                 `protobuf:"bytes,3,opt,name=invited_by,json=invitedBy,proto3" json:"invited_by,omitempty"`
	Email          string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	RoleIds        []string               `protobuf:"bytes,5,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	InvitedAt      string                 `protobuf:"bytes,6,opt,name=invited_at,json=invitedAt,proto3" json:"invited_at,omitempty"` // RFC3339
	IsAccepted     bool                   `protobuf:"varint,7,opt,name=is_accepted,json=isAccepted,proto3" json:"is_accepted,omitempty"`
	AcceptedAt     *string                `protobuf:"bytes,8,opt,name=accepted_at,json=acceptedAt,proto3,oneof" json:"accepted_at,omitempty"`
	ExpiredAt      string                 `protobuf:"bytes,9,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"` // RFC3339
	IsPending      bool                   `protobuf:"varint,10,opt,name=is_pending,json=isPending,proto3" json:"is_pending,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrganizationMemberInvitation) Reset() {
	*x = OrganizationMemberInvitation{}
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationMemberInvitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationMemberInvitation) ProtoMessage() {}

func (x *OrganizationMemberInvitation) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationMemberInvitation.ProtoReflect.Descriptor instead.
func (*OrganizationMemberInvitation) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_invitation_proto_rawDescGZIP(), []int{7}
}

func (x *OrganizationMemberInvitation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrganizationMemberInvitation) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *OrganizationMemberInvitation) GetInvitedBy() string {
	if x != nil {
		return x.InvitedBy
	}
	return ""
}

func (x *OrganizationMemberInvitation) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OrganizationMemberInvitation) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *OrganizationMemberInvitation) GetInvitedAt() string {
	if x != nil {
		return x.InvitedAt
	}
	return ""
}

func (x *OrganizationMemberInvitation) GetIsAccepted() bool {
	if x != nil {
		return x.IsAccepted
	}
	return false
}

func (x *OrganizationMemberInvitation) GetAcceptedAt() string {
	if x != nil && x.AcceptedAt != nil {
		return *x.AcceptedAt
	}
	return ""
}

func (x *OrganizationMemberInvitation) GetExpiredAt() string {
	if x != nil {
		return x.ExpiredAt
	}
	return ""
}

func (x *OrganizationMemberInvitation) GetIsPending() bool {
	if x != nil {
		return x.IsPending
	}
	return false
}

type InvitedBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvitedBy) Reset() {
	*x = InvitedBy{}
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvitedBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvitedBy) ProtoMessage() {}

func (x *InvitedBy) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvitedBy.ProtoReflect.Descriptor instead.
func (*InvitedBy) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_invitation_proto_rawDescGZIP(), []int{8}
}

func (x *InvitedBy) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *InvitedBy) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *InvitedBy) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type OrganizationMemberInvitationForOrg struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Invitation    *OrganizationMemberInvitation `protobuf:"bytes,1,opt,name=invitation,proto3" json:"invitation,omitempty"`
	InvitedBy     *InvitedBy                    `protobuf:"bytes,2,opt,name=invited_by,json=invitedBy,proto3" json:"invited_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationMemberInvitationForOrg) Reset() {
	*x = OrganizationMemberInvitationForOrg{}
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationMemberInvitationForOrg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationMemberInvitationForOrg) ProtoMessage() {}

func (x *OrganizationMemberInvitationForOrg) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationMemberInvitationForOrg.ProtoReflect.Descriptor instead.
func (*OrganizationMemberInvitationForOrg) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_invitation_proto_rawDescGZIP(), []int{9}
}

func (x *OrganizationMemberInvitationForOrg) GetInvitation() *OrganizationMemberInvitation {
	if x != nil {
		return x.Invitation
	}
	return nil
}

func (x *OrganizationMemberInvitationForOrg) GetInvitedBy() *InvitedBy {
	if x != nil {
		return x.InvitedBy
	}
	return nil
}

type ListOrgInvitationsResponseForOrg struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Invitations   []*OrganizationMemberInvitationForOrg `protobuf:"bytes,1,rep,name=invitations,proto3" json:"invitations,omitempty"`
	TotalCount    int32                                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	NextPageToken string                                `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrgInvitationsResponseForOrg) Reset() {
	*x = ListOrgInvitationsResponseForOrg{}
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrgInvitationsResponseForOrg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrgInvitationsResponseForOrg) ProtoMessage() {}

func (x *ListOrgInvitationsResponseForOrg) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_invitation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrgInvitationsResponseForOrg.ProtoReflect.Descriptor instead.
func (*ListOrgInvitationsResponseForOrg) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_invitation_proto_rawDescGZIP(), []int{10}
}

func (x *ListOrgInvitationsResponseForOrg) GetInvitations() []*OrganizationMemberInvitationForOrg {
	if x != nil {
		return x.Invitations
	}
	return nil
}

func (x *ListOrgInvitationsResponseForOrg) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListOrgInvitationsResponseForOrg) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_tenant_v1_organization_invitation_proto protoreflect.FileDescriptor

const file_tenant_v1_organization_invitation_proto_rawDesc = "" +
	"\n" +
	"'tenant/v1/organization_invitation.proto\x12\ttenant.v1\x1a\x1bbuf/validate/validate.proto\x1a\x16tenant/v1/common.proto\x1a$tenant/v1/organization_options.proto\"\x93\x01\n" +
	"\x17CreateInvitationRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12\x1d\n" +
	"\x05email\x18\x02 \x01(\tB\a\xbaH\x04r\x02`\x01R\x05email\x12'\n" +
	"\brole_ids\x18\x03 \x03(\tB\f\xbaH\t\x92\x01\x06\"\x04r\x02\x10\x01R\aroleIds\"\x9b\x01\n" +
	"\x16ListInvitationsRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12&\n" +
	"\tpage_size\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x00R\bpageSize\x12'\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\tpageToken\"=\n" +
	"\x1cGetPendingInvitationsRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xbaH\x04r\x02`\x01R\x05email\"8\n" +
	"\x17AcceptInvitationRequest\x12\x1d\n" +
	"\x05token\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05token\"p\n" +
	"\x17CancelInvitationRequest\x12,\n" +
	"\rinvitation_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\finvitationId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\"o\n" +
	"$OrganizationMemberInvitationResponse\x12G\n" +
	"\n" +
	"invitation\x18\x01 \x01(\v2'.tenant.v1.OrganizationMemberInvitationR\n" +
	"invitation\"\xb9\x01\n" +
	"#ListOrganizationInvitationsResponse\x12I\n" +
	"\vinvitations\x18\x01 \x03(\v2'.tenant.v1.OrganizationMemberInvitationR\vinvitations\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"\xdb\x02\n" +
	"\x1cOrganizationMemberInvitation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"invited_by\x18\x03 \x01(\tR\tinvitedBy\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x19\n" +
	"\brole_ids\x18\x05 \x03(\tR\aroleIds\x12\x1d\n" +
	"\n" +
	"invited_at\x18\x06 \x01(\tR\tinvitedAt\x12\x1f\n" +
	"\vis_accepted\x18\a \x01(\bR\n" +
	"isAccepted\x12$\n" +
	"\vaccepted_at\x18\b \x01(\tH\x00R\n" +
	"acceptedAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"expired_at\x18\t \x01(\tR\texpiredAt\x12\x1d\n" +
	"\n" +
	"is_pending\x18\n" +
	" \x01(\bR\tisPendingB\x0e\n" +
	"\f_accepted_at\"[\n" +
	"\tInvitedBy\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\xa2\x01\n" +
	"\"OrganizationMemberInvitationForOrg\x12G\n" +
	"\n" +
	"invitation\x18\x01 \x01(\v2'.tenant.v1.OrganizationMemberInvitationR\n" +
	"invitation\x123\n" +
	"\n" +
	"invited_by\x18\x02 \x01(\v2\x14.tenant.v1.InvitedByR\tinvitedBy\"\xbc\x01\n" +
	" ListOrgInvitationsResponseForOrg\x12O\n" +
	"\vinvitations\x18\x01 \x03(\v2-.tenant.v1.OrganizationMemberInvitationForOrgR\vinvitations\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken2\xae\x05\n" +
	"\x1dOrganizationInvitationService\x12]\n" +
	"\x10AcceptInvitation\x12\".tenant.v1.AcceptInvitationRequest\x1a .tenant.v1.TenantSuccessResponse\"\x03\xc8>\x01\x12]\n" +
	"\x10CancelInvitation\x12\".tenant.v1.CancelInvitationRequest\x1a .tenant.v1.TenantSuccessResponse\"\x03\xc8>\x01\x12u\n" +
	"\x15GetPendingInvitations\x12'.tenant.v1.GetPendingInvitationsRequest\x1a..tenant.v1.ListOrganizationInvitationsResponse\"\x03\xc8>\x01\x12j\n" +
	"\x10CreateInvitation\x12\".tenant.v1.CreateInvitationRequest\x1a .tenant.v1.TenantSuccessResponse\"\x10\xd2>\rmember.invite\x12t\n" +
	"\x0fListInvitations\x12!.tenant.v1.ListInvitationsRequest\x1a..tenant.v1.ListOrganizationInvitationsResponse\"\x0e\xd2>\vmember.list\x12v\n" +
	"\x0fGetPendingByOrg\x12&.tenant.v1.TenantOrganizationIDRequest\x1a+.tenant.v1.ListOrgInvitationsResponseForOrg\"\x0e\xd2>\vmember.listB7Z5github.com/vyolayer/vyolayer/proto/tenant/v1;tenantV1b\x06proto3"

var (
	file_tenant_v1_organization_invitation_proto_rawDescOnce sync.Once
	file_tenant_v1_organization_invitation_proto_rawDescData []byte
)

func file_tenant_v1_organization_invitation_proto_rawDescGZIP() []byte {
	file_tenant_v1_organization_invitation_proto_rawDescOnce.Do(func() {
		file_tenant_v1_organization_invitation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenant_v1_organization_invitation_proto_rawDesc), len(file_tenant_v1_organization_invitation_proto_rawDesc)))
	})
	return file_tenant_v1_organization_invitation_proto_rawDescData
}

var file_tenant_v1_organization_invitation_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_tenant_v1_organization_invitation_proto_goTypes = []any{
	(*CreateInvitationRequest)(nil),              // 0: tenant.v1.CreateInvitationRequest
	(*ListInvitationsRequest)(nil),               // 1: tenant.v1.ListInvitationsRequest
	(*GetPendingInvitationsRequest)(nil),         // 2: tenant.v1.GetPendingInvitationsRequest
	(*AcceptInvitationRequest)(nil),              // 3: tenant.v1.AcceptInvitationRequest
	(*CancelInvitationRequest)(nil),              // 4: tenant.v1.CancelInvitationRequest
	(*OrganizationMemberInvitationResponse)(nil), // 5: tenant.v1.OrganizationMemberInvitationResponse
	(*ListOrganizationInvitationsResponse)(nil),  // 6: tenant.v1.ListOrganizationInvitationsResponse
	(*OrganizationMemberInvitation)(nil),         // 7: tenant.v1.OrganizationMemberInvitation
	(*InvitedBy)(nil),                            // 8: tenant.v1.InvitedBy
	(*OrganizationMemberInvitationForOrg)(nil),   // 9: tenant.v1.OrganizationMemberInvitationForOrg
	(*ListOrgInvitationsResponseForOrg)(nil),     // 10: tenant.v1.ListOrgInvitationsResponseForOrg
	(*TenantOrganizationIDRequest)(nil),          // 11: tenant.v1.TenantOrganizationIDRequest
	(*TenantSuccessResponse)(nil),                // 12: tenant.v1.TenantSuccessResponse
}
var file_tenant_v1_organization_invitation_proto_depIdxs = []int32{
	7,  // 0: tenant.v1.OrganizationMemberInvitationResponse.invitation:type_name -> tenant.v1.OrganizationMemberInvitation
	7,  // 1: tenant.v1.ListOrganizationInvitationsResponse.invitations:type_name -> tenant.v1.OrganizationMemberInvitation
	7,  // 2: tenant.v1.OrganizationMemberInvitationForOrg.invitation:type_name -> tenant.v1.OrganizationMemberInvitation
	8,  // 3: tenant.v1.OrganizationMemberInvitationForOrg.invited_by:type_name -> tenant.v1.InvitedBy
	9,  // 4: tenant.v1.ListOrgInvitationsResponseForOrg.invitations:type_name -> tenant.v1.OrganizationMemberInvitationForOrg
	3,  // 5: tenant.v1.OrganizationInvitationService.AcceptInvitation:input_type -> tenant.v1.AcceptInvitationRequest
	4,  // 6: tenant.v1.OrganizationInvitationService.CancelInvitation:input_type -> tenant.v1.CancelInvitationRequest
	2,  // 7: tenant.v1.OrganizationInvitationService.GetPendingInvitations:input_type -> tenant.v1.GetPendingInvitationsRequest
	0,  // 8: tenant.v1.OrganizationInvitationService.CreateInvitation:input_type -> tenant.v1.CreateInvitationRequest
	1,  // 9: tenant.v1.OrganizationInvitationService.ListInvitations:input_type -> tenant.v1.ListInvitationsRequest
	11, // 10: tenant.v1.OrganizationInvitationService.GetPendingByOrg:input_type -> tenant.v1.TenantOrganizationIDRequest
	12, // 11: tenant.v1.OrganizationInvitationService.AcceptInvitation:output_type -> tenant.v1.TenantSuccessResponse
	12, // 12: tenant.v1.OrganizationInvitationService.CancelInvitation:output_type -> tenant.v1.TenantSuccessResponse
	6,  // 13: tenant.v1.OrganizationInvitationService.GetPendingInvitations:output_type -> tenant.v1.ListOrganizationInvitationsResponse
	12, // 14: tenant.v1.OrganizationInvitationService.CreateInvitation:output_type -> tenant.v1.TenantSuccessResponse
	6,  // 15: tenant.v1.OrganizationInvitationService.ListInvitations:output_type -> tenant.v1.ListOrganizationInvitationsResponse
	10, // 16: tenant.v1.OrganizationInvitationService.GetPendingByOrg:output_type -> tenant.v1.ListOrgInvitationsResponseForOrg
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_tenant_v1_organization_invitation_proto_init() }
func file_tenant_v1_organization_invitation_proto_init() {
	if File_tenant_v1_organization_invitation_proto != nil {
		return
	}
	file_tenant_v1_common_proto_init()
	file_tenant_v1_organization_options_proto_init()
	file_tenant_v1_organization_invitation_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_v1_organization_invitation_proto_rawDesc), len(file_tenant_v1_organization_invitation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenant_v1_organization_invitation_proto_goTypes,
		DependencyIndexes: file_tenant_v1_organization_invitation_proto_depIdxs,
		MessageInfos:      file_tenant_v1_organization_invitation_proto_msgTypes,
	}.Build()
	File_tenant_v1_organization_invitation_proto = out.File
	file_tenant_v1_organization_invitation_proto_goTypes = nil
	file_tenant_v1_organization_invitation_proto_depIdxs = nil
}
