// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: tenant/v1/organization_member.proto

package tenantV1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrganizationMemberService_GetCurrentMember_FullMethodName   = "/tenant.v1.OrganizationMemberService/GetCurrentMember"
	OrganizationMemberService_GetAllMembersByOrg_FullMethodName = "/tenant.v1.OrganizationMemberService/GetAllMembersByOrg"
	OrganizationMemberService_GetMemberById_FullMethodName      = "/tenant.v1.OrganizationMemberService/GetMemberById"
	OrganizationMemberService_RemoveMember_FullMethodName       = "/tenant.v1.OrganizationMemberService/RemoveMember"
	OrganizationMemberService_ChangeMemberRole_FullMethodName   = "/tenant.v1.OrganizationMemberService/ChangeMemberRole"
)

// OrganizationMemberServiceClient is the client API for OrganizationMemberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrganizationMemberServiceClient interface {
	// No permission needed—if they pass the standard interceptor, they are a member and can view themselves.
	GetCurrentMember(ctx context.Context, in *TenantOrganizationIDRequest, opts ...grpc.CallOption) (*OrganizationMemberWithRBACResponse, error)
	GetAllMembersByOrg(ctx context.Context, in *TenantOrganizationIDRequest, opts ...grpc.CallOption) (*ListOrganizationMembersResponse, error)
	GetMemberById(ctx context.Context, in *GetOrganizationMemberByIdRequest, opts ...grpc.CallOption) (*OrganizationMemberResponse, error)
	RemoveMember(ctx context.Context, in *RemoveOrganizationMemberRequest, opts ...grpc.CallOption) (*TenantSuccessResponse, error)
	ChangeMemberRole(ctx context.Context, in *ChangeOrganizationMemberRoleRequest, opts ...grpc.CallOption) (*TenantSuccessResponse, error)
}

type organizationMemberServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrganizationMemberServiceClient(cc grpc.ClientConnInterface) OrganizationMemberServiceClient {
	return &organizationMemberServiceClient{cc}
}

func (c *organizationMemberServiceClient) GetCurrentMember(ctx context.Context, in *TenantOrganizationIDRequest, opts ...grpc.CallOption) (*OrganizationMemberWithRBACResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrganizationMemberWithRBACResponse)
	err := c.cc.Invoke(ctx, OrganizationMemberService_GetCurrentMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationMemberServiceClient) GetAllMembersByOrg(ctx context.Context, in *TenantOrganizationIDRequest, opts ...grpc.CallOption) (*ListOrganizationMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrganizationMembersResponse)
	err := c.cc.Invoke(ctx, OrganizationMemberService_GetAllMembersByOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationMemberServiceClient) GetMemberById(ctx context.Context, in *GetOrganizationMemberByIdRequest, opts ...grpc.CallOption) (*OrganizationMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrganizationMemberResponse)
	err := c.cc.Invoke(ctx, OrganizationMemberService_GetMemberById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationMemberServiceClient) RemoveMember(ctx context.Context, in *RemoveOrganizationMemberRequest, opts ...grpc.CallOption) (*TenantSuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantSuccessResponse)
	err := c.cc.Invoke(ctx, OrganizationMemberService_RemoveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationMemberServiceClient) ChangeMemberRole(ctx context.Context, in *ChangeOrganizationMemberRoleRequest, opts ...grpc.CallOption) (*TenantSuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantSuccessResponse)
	err := c.cc.Invoke(ctx, OrganizationMemberService_ChangeMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrganizationMemberServiceServer is the server API for OrganizationMemberService service.
// All implementations must embed UnimplementedOrganizationMemberServiceServer
// for forward compatibility.
type OrganizationMemberServiceServer interface {
	// No permission needed—if they pass the standard interceptor, they are a member and can view themselves.
	GetCurrentMember(context.Context, *TenantOrganizationIDRequest) (*OrganizationMemberWithRBACResponse, error)
	GetAllMembersByOrg(context.Context, *TenantOrganizationIDRequest) (*ListOrganizationMembersResponse, error)
	GetMemberById(context.Context, *GetOrganizationMemberByIdRequest) (*OrganizationMemberResponse, error)
	RemoveMember(context.Context, *RemoveOrganizationMemberRequest) (*TenantSuccessResponse, error)
	ChangeMemberRole(context.Context, *ChangeOrganizationMemberRoleRequest) (*TenantSuccessResponse, error)
	mustEmbedUnimplementedOrganizationMemberServiceServer()
}

// UnimplementedOrganizationMemberServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrganizationMemberServiceServer struct{}

func (UnimplementedOrganizationMemberServiceServer) GetCurrentMember(context.Context, *TenantOrganizationIDRequest) (*OrganizationMemberWithRBACResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentMember not implemented")
}
func (UnimplementedOrganizationMemberServiceServer) GetAllMembersByOrg(context.Context, *TenantOrganizationIDRequest) (*ListOrganizationMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllMembersByOrg not implemented")
}
func (UnimplementedOrganizationMemberServiceServer) GetMemberById(context.Context, *GetOrganizationMemberByIdRequest) (*OrganizationMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemberById not implemented")
}
func (UnimplementedOrganizationMemberServiceServer) RemoveMember(context.Context, *RemoveOrganizationMemberRequest) (*TenantSuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMember not implemented")
}
func (UnimplementedOrganizationMemberServiceServer) ChangeMemberRole(context.Context, *ChangeOrganizationMemberRoleRequest) (*TenantSuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeMemberRole not implemented")
}
func (UnimplementedOrganizationMemberServiceServer) mustEmbedUnimplementedOrganizationMemberServiceServer() {
}
func (UnimplementedOrganizationMemberServiceServer) testEmbeddedByValue() {}

// UnsafeOrganizationMemberServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrganizationMemberServiceServer will
// result in compilation errors.
type UnsafeOrganizationMemberServiceServer interface {
	mustEmbedUnimplementedOrganizationMemberServiceServer()
}

func RegisterOrganizationMemberServiceServer(s grpc.ServiceRegistrar, srv OrganizationMemberServiceServer) {
	// If the following call panics, it indicates UnimplementedOrganizationMemberServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrganizationMemberService_ServiceDesc, srv)
}

func _OrganizationMemberService_GetCurrentMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantOrganizationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationMemberServiceServer).GetCurrentMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationMemberService_GetCurrentMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationMemberServiceServer).GetCurrentMember(ctx, req.(*TenantOrganizationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationMemberService_GetAllMembersByOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantOrganizationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationMemberServiceServer).GetAllMembersByOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationMemberService_GetAllMembersByOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationMemberServiceServer).GetAllMembersByOrg(ctx, req.(*TenantOrganizationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationMemberService_GetMemberById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrganizationMemberByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationMemberServiceServer).GetMemberById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationMemberService_GetMemberById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationMemberServiceServer).GetMemberById(ctx, req.(*GetOrganizationMemberByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationMemberService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveOrganizationMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationMemberServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationMemberService_RemoveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationMemberServiceServer).RemoveMember(ctx, req.(*RemoveOrganizationMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationMemberService_ChangeMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeOrganizationMemberRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationMemberServiceServer).ChangeMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationMemberService_ChangeMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationMemberServiceServer).ChangeMemberRole(ctx, req.(*ChangeOrganizationMemberRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrganizationMemberService_ServiceDesc is the grpc.ServiceDesc for OrganizationMemberService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrganizationMemberService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tenant.v1.OrganizationMemberService",
	HandlerType: (*OrganizationMemberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentMember",
			Handler:    _OrganizationMemberService_GetCurrentMember_Handler,
		},
		{
			MethodName: "GetAllMembersByOrg",
			Handler:    _OrganizationMemberService_GetAllMembersByOrg_Handler,
		},
		{
			MethodName: "GetMemberById",
			Handler:    _OrganizationMemberService_GetMemberById_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _OrganizationMemberService_RemoveMember_Handler,
		},
		{
			MethodName: "ChangeMemberRole",
			Handler:    _OrganizationMemberService_ChangeMemberRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tenant/v1/organization_member.proto",
}
