// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tenant/v1/organization_member.proto

package tenantV1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------
// Member Requests
// --------------------
type GetOrganizationMemberByIdRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	MemberId       string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrganizationMemberByIdRequest) Reset() {
	*x = GetOrganizationMemberByIdRequest{}
	mi := &file_tenant_v1_organization_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationMemberByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationMemberByIdRequest) ProtoMessage() {}

func (x *GetOrganizationMemberByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationMemberByIdRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationMemberByIdRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_member_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrganizationMemberByIdRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetOrganizationMemberByIdRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type RemoveOrganizationMemberRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	MemberId       string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveOrganizationMemberRequest) Reset() {
	*x = RemoveOrganizationMemberRequest{}
	mi := &file_tenant_v1_organization_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveOrganizationMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOrganizationMemberRequest) ProtoMessage() {}

func (x *RemoveOrganizationMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOrganizationMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveOrganizationMemberRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_member_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveOrganizationMemberRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *RemoveOrganizationMemberRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type ChangeOrganizationMemberRoleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	MemberId       string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	RoleId         string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChangeOrganizationMemberRoleRequest) Reset() {
	*x = ChangeOrganizationMemberRoleRequest{}
	mi := &file_tenant_v1_organization_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeOrganizationMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeOrganizationMemberRoleRequest) ProtoMessage() {}

func (x *ChangeOrganizationMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeOrganizationMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*ChangeOrganizationMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_member_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeOrganizationMemberRoleRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ChangeOrganizationMemberRoleRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *ChangeOrganizationMemberRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

// --------------------
// Member Responses
// --------------------
type ListOrganizationMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*OrganizationMember  `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationMembersResponse) Reset() {
	*x = ListOrganizationMembersResponse{}
	mi := &file_tenant_v1_organization_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationMembersResponse) ProtoMessage() {}

func (x *ListOrganizationMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationMembersResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationMembersResponse) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_member_proto_rawDescGZIP(), []int{3}
}

func (x *ListOrganizationMembersResponse) GetMembers() []*OrganizationMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListOrganizationMembersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListOrganizationMembersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type OrganizationMemberWithRBACResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Member        *OrganizationMember       `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	Roles         []*OrganizationRole       `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions   []*OrganizationPermission `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationMemberWithRBACResponse) Reset() {
	*x = OrganizationMemberWithRBACResponse{}
	mi := &file_tenant_v1_organization_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationMemberWithRBACResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationMemberWithRBACResponse) ProtoMessage() {}

func (x *OrganizationMemberWithRBACResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationMemberWithRBACResponse.ProtoReflect.Descriptor instead.
func (*OrganizationMemberWithRBACResponse) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_member_proto_rawDescGZIP(), []int{4}
}

func (x *OrganizationMemberWithRBACResponse) GetMember() *OrganizationMember {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *OrganizationMemberWithRBACResponse) GetRoles() []*OrganizationRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *OrganizationMemberWithRBACResponse) GetPermissions() []*OrganizationPermission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type OrganizationMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *OrganizationMember    `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationMemberResponse) Reset() {
	*x = OrganizationMemberResponse{}
	mi := &file_tenant_v1_organization_member_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationMemberResponse) ProtoMessage() {}

func (x *OrganizationMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_member_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationMemberResponse.ProtoReflect.Descriptor instead.
func (*OrganizationMemberResponse) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_member_proto_rawDescGZIP(), []int{5}
}

func (x *OrganizationMemberResponse) GetMember() *OrganizationMember {
	if x != nil {
		return x.Member
	}
	return nil
}

// --------------------
// Member Messages
// --------------------
type OrganizationMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	JoinedAt      string                 `protobuf:"bytes,6,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"` // RFC3339 string
	InvitedBy     *string                `protobuf:"bytes,7,opt,name=invited_by,json=invitedBy,proto3,oneof" json:"invited_by,omitempty"`
	InvitedAt     *string                `protobuf:"bytes,8,opt,name=invited_at,json=invitedAt,proto3,oneof" json:"invited_at,omitempty"`
	DeactivatedBy *string                `protobuf:"bytes,9,opt,name=deactivated_by,json=deactivatedBy,proto3,oneof" json:"deactivated_by,omitempty"`
	DeactivatedAt *string                `protobuf:"bytes,10,opt,name=deactivated_at,json=deactivatedAt,proto3,oneof" json:"deactivated_at,omitempty"`
	Roles         []*OrganizationRole    `protobuf:"bytes,11,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationMember) Reset() {
	*x = OrganizationMember{}
	mi := &file_tenant_v1_organization_member_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationMember) ProtoMessage() {}

func (x *OrganizationMember) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_organization_member_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationMember.ProtoReflect.Descriptor instead.
func (*OrganizationMember) Descriptor() ([]byte, []int) {
	return file_tenant_v1_organization_member_proto_rawDescGZIP(), []int{6}
}

func (x *OrganizationMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrganizationMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrganizationMember) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OrganizationMember) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *OrganizationMember) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrganizationMember) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

func (x *OrganizationMember) GetInvitedBy() string {
	if x != nil && x.InvitedBy != nil {
		return *x.InvitedBy
	}
	return ""
}

func (x *OrganizationMember) GetInvitedAt() string {
	if x != nil && x.InvitedAt != nil {
		return *x.InvitedAt
	}
	return ""
}

func (x *OrganizationMember) GetDeactivatedBy() string {
	if x != nil && x.DeactivatedBy != nil {
		return *x.DeactivatedBy
	}
	return ""
}

func (x *OrganizationMember) GetDeactivatedAt() string {
	if x != nil && x.DeactivatedAt != nil {
		return *x.DeactivatedAt
	}
	return ""
}

func (x *OrganizationMember) GetRoles() []*OrganizationRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_tenant_v1_organization_member_proto protoreflect.FileDescriptor

const file_tenant_v1_organization_member_proto_rawDesc = "" +
	"\n" +
	"#tenant/v1/organization_member.proto\x12\ttenant.v1\x1a\x1bbuf/validate/validate.proto\x1a\x16tenant/v1/common.proto\x1a$tenant/v1/organization_options.proto\"z\n" +
	" GetOrganizationMemberByIdRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12$\n" +
	"\tmember_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bmemberId\"y\n" +
	"\x1fRemoveOrganizationMemberRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12$\n" +
	"\tmember_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bmemberId\"\x9f\x01\n" +
	"#ChangeOrganizationMemberRoleRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12$\n" +
	"\tmember_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bmemberId\x12 \n" +
	"\arole_id\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roleId\"\xa3\x01\n" +
	"\x1fListOrganizationMembersResponse\x127\n" +
	"\amembers\x18\x01 \x03(\v2\x1d.tenant.v1.OrganizationMemberR\amembers\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"\xd3\x01\n" +
	"\"OrganizationMemberWithRBACResponse\x125\n" +
	"\x06member\x18\x01 \x01(\v2\x1d.tenant.v1.OrganizationMemberR\x06member\x121\n" +
	"\x05roles\x18\x02 \x03(\v2\x1b.tenant.v1.OrganizationRoleR\x05roles\x12C\n" +
	"\vpermissions\x18\x03 \x03(\v2!.tenant.v1.OrganizationPermissionR\vpermissions\"S\n" +
	"\x1aOrganizationMemberResponse\x125\n" +
	"\x06member\x18\x01 \x01(\v2\x1d.tenant.v1.OrganizationMemberR\x06member\"\xbc\x03\n" +
	"\x12OrganizationMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\tjoined_at\x18\x06 \x01(\tR\bjoinedAt\x12\"\n" +
	"\n" +
	"invited_by\x18\a \x01(\tH\x00R\tinvitedBy\x88\x01\x01\x12\"\n" +
	"\n" +
	"invited_at\x18\b \x01(\tH\x01R\tinvitedAt\x88\x01\x01\x12*\n" +
	"\x0edeactivated_by\x18\t \x01(\tH\x02R\rdeactivatedBy\x88\x01\x01\x12*\n" +
	"\x0edeactivated_at\x18\n" +
	" \x01(\tH\x03R\rdeactivatedAt\x88\x01\x01\x121\n" +
	"\x05roles\x18\v \x03(\v2\x1b.tenant.v1.OrganizationRoleR\x05rolesB\r\n" +
	"\v_invited_byB\r\n" +
	"\v_invited_atB\x11\n" +
	"\x0f_deactivated_byB\x11\n" +
	"\x0f_deactivated_at2\xdd\x04\n" +
	"\x19OrganizationMemberService\x12i\n" +
	"\x10GetCurrentMember\x12&.tenant.v1.TenantOrganizationIDRequest\x1a-.tenant.v1.OrganizationMemberWithRBACResponse\x12x\n" +
	"\x12GetAllMembersByOrg\x12&.tenant.v1.TenantOrganizationIDRequest\x1a*.tenant.v1.ListOrganizationMembersResponse\"\x0e\xd2>\vmember.list\x12s\n" +
	"\rGetMemberById\x12+.tenant.v1.GetOrganizationMemberByIdRequest\x1a%.tenant.v1.OrganizationMemberResponse\"\x0e\xd2>\vmember.view\x12n\n" +
	"\fRemoveMember\x12*.tenant.v1.RemoveOrganizationMemberRequest\x1a .tenant.v1.TenantSuccessResponse\"\x10\xd2>\rmember.remove\x12v\n" +
	"\x10ChangeMemberRole\x12..tenant.v1.ChangeOrganizationMemberRoleRequest\x1a .tenant.v1.TenantSuccessResponse\"\x10\xd2>\rmember.updateB7Z5github.com/vyolayer/vyolayer/proto/tenant/v1;tenantV1b\x06proto3"

var (
	file_tenant_v1_organization_member_proto_rawDescOnce sync.Once
	file_tenant_v1_organization_member_proto_rawDescData []byte
)

func file_tenant_v1_organization_member_proto_rawDescGZIP() []byte {
	file_tenant_v1_organization_member_proto_rawDescOnce.Do(func() {
		file_tenant_v1_organization_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenant_v1_organization_member_proto_rawDesc), len(file_tenant_v1_organization_member_proto_rawDesc)))
	})
	return file_tenant_v1_organization_member_proto_rawDescData
}

var file_tenant_v1_organization_member_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tenant_v1_organization_member_proto_goTypes = []any{
	(*GetOrganizationMemberByIdRequest)(nil),    // 0: tenant.v1.GetOrganizationMemberByIdRequest
	(*RemoveOrganizationMemberRequest)(nil),     // 1: tenant.v1.RemoveOrganizationMemberRequest
	(*ChangeOrganizationMemberRoleRequest)(nil), // 2: tenant.v1.ChangeOrganizationMemberRoleRequest
	(*ListOrganizationMembersResponse)(nil),     // 3: tenant.v1.ListOrganizationMembersResponse
	(*OrganizationMemberWithRBACResponse)(nil),  // 4: tenant.v1.OrganizationMemberWithRBACResponse
	(*OrganizationMemberResponse)(nil),          // 5: tenant.v1.OrganizationMemberResponse
	(*OrganizationMember)(nil),                  // 6: tenant.v1.OrganizationMember
	(*OrganizationRole)(nil),                    // 7: tenant.v1.OrganizationRole
	(*OrganizationPermission)(nil),              // 8: tenant.v1.OrganizationPermission
	(*TenantOrganizationIDRequest)(nil),         // 9: tenant.v1.TenantOrganizationIDRequest
	(*TenantSuccessResponse)(nil),               // 10: tenant.v1.TenantSuccessResponse
}
var file_tenant_v1_organization_member_proto_depIdxs = []int32{
	6,  // 0: tenant.v1.ListOrganizationMembersResponse.members:type_name -> tenant.v1.OrganizationMember
	6,  // 1: tenant.v1.OrganizationMemberWithRBACResponse.member:type_name -> tenant.v1.OrganizationMember
	7,  // 2: tenant.v1.OrganizationMemberWithRBACResponse.roles:type_name -> tenant.v1.OrganizationRole
	8,  // 3: tenant.v1.OrganizationMemberWithRBACResponse.permissions:type_name -> tenant.v1.OrganizationPermission
	6,  // 4: tenant.v1.OrganizationMemberResponse.member:type_name -> tenant.v1.OrganizationMember
	7,  // 5: tenant.v1.OrganizationMember.roles:type_name -> tenant.v1.OrganizationRole
	9,  // 6: tenant.v1.OrganizationMemberService.GetCurrentMember:input_type -> tenant.v1.TenantOrganizationIDRequest
	9,  // 7: tenant.v1.OrganizationMemberService.GetAllMembersByOrg:input_type -> tenant.v1.TenantOrganizationIDRequest
	0,  // 8: tenant.v1.OrganizationMemberService.GetMemberById:input_type -> tenant.v1.GetOrganizationMemberByIdRequest
	1,  // 9: tenant.v1.OrganizationMemberService.RemoveMember:input_type -> tenant.v1.RemoveOrganizationMemberRequest
	2,  // 10: tenant.v1.OrganizationMemberService.ChangeMemberRole:input_type -> tenant.v1.ChangeOrganizationMemberRoleRequest
	4,  // 11: tenant.v1.OrganizationMemberService.GetCurrentMember:output_type -> tenant.v1.OrganizationMemberWithRBACResponse
	3,  // 12: tenant.v1.OrganizationMemberService.GetAllMembersByOrg:output_type -> tenant.v1.ListOrganizationMembersResponse
	5,  // 13: tenant.v1.OrganizationMemberService.GetMemberById:output_type -> tenant.v1.OrganizationMemberResponse
	10, // 14: tenant.v1.OrganizationMemberService.RemoveMember:output_type -> tenant.v1.TenantSuccessResponse
	10, // 15: tenant.v1.OrganizationMemberService.ChangeMemberRole:output_type -> tenant.v1.TenantSuccessResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_tenant_v1_organization_member_proto_init() }
func file_tenant_v1_organization_member_proto_init() {
	if File_tenant_v1_organization_member_proto != nil {
		return
	}
	file_tenant_v1_common_proto_init()
	file_tenant_v1_organization_options_proto_init()
	file_tenant_v1_organization_member_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_v1_organization_member_proto_rawDesc), len(file_tenant_v1_organization_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenant_v1_organization_member_proto_goTypes,
		DependencyIndexes: file_tenant_v1_organization_member_proto_depIdxs,
		MessageInfos:      file_tenant_v1_organization_member_proto_msgTypes,
	}.Build()
	File_tenant_v1_organization_member_proto = out.File
	file_tenant_v1_organization_member_proto_goTypes = nil
	file_tenant_v1_organization_member_proto_depIdxs = nil
}
