// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: tenant/v1/organization_invitation.proto

package tenantV1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrganizationInvitationService_AcceptInvitation_FullMethodName      = "/tenant.v1.OrganizationInvitationService/AcceptInvitation"
	OrganizationInvitationService_CancelInvitation_FullMethodName      = "/tenant.v1.OrganizationInvitationService/CancelInvitation"
	OrganizationInvitationService_GetPendingInvitations_FullMethodName = "/tenant.v1.OrganizationInvitationService/GetPendingInvitations"
	OrganizationInvitationService_CreateInvitation_FullMethodName      = "/tenant.v1.OrganizationInvitationService/CreateInvitation"
	OrganizationInvitationService_ListInvitations_FullMethodName       = "/tenant.v1.OrganizationInvitationService/ListInvitations"
	OrganizationInvitationService_GetPendingByOrg_FullMethodName       = "/tenant.v1.OrganizationInvitationService/GetPendingByOrg"
)

// OrganizationInvitationServiceClient is the client API for OrganizationInvitationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrganizationInvitationServiceClient interface {
	// --- Public / Bypasses Org Check ---
	AcceptInvitation(ctx context.Context, in *AcceptInvitationRequest, opts ...grpc.CallOption) (*TenantSuccessResponse, error)
	// A user canceling their own pending invite doesn't require org membership yet
	CancelInvitation(ctx context.Context, in *CancelInvitationRequest, opts ...grpc.CallOption) (*TenantSuccessResponse, error)
	GetPendingInvitations(ctx context.Context, in *GetPendingInvitationsRequest, opts ...grpc.CallOption) (*ListOrganizationInvitationsResponse, error)
	// --- Requires Org Membership ---
	CreateInvitation(ctx context.Context, in *CreateInvitationRequest, opts ...grpc.CallOption) (*TenantSuccessResponse, error)
	ListInvitations(ctx context.Context, in *ListInvitationsRequest, opts ...grpc.CallOption) (*ListOrganizationInvitationsResponse, error)
	GetPendingByOrg(ctx context.Context, in *TenantOrganizationIDRequest, opts ...grpc.CallOption) (*ListOrgInvitationsResponseForOrg, error)
}

type organizationInvitationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrganizationInvitationServiceClient(cc grpc.ClientConnInterface) OrganizationInvitationServiceClient {
	return &organizationInvitationServiceClient{cc}
}

func (c *organizationInvitationServiceClient) AcceptInvitation(ctx context.Context, in *AcceptInvitationRequest, opts ...grpc.CallOption) (*TenantSuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantSuccessResponse)
	err := c.cc.Invoke(ctx, OrganizationInvitationService_AcceptInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationInvitationServiceClient) CancelInvitation(ctx context.Context, in *CancelInvitationRequest, opts ...grpc.CallOption) (*TenantSuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantSuccessResponse)
	err := c.cc.Invoke(ctx, OrganizationInvitationService_CancelInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationInvitationServiceClient) GetPendingInvitations(ctx context.Context, in *GetPendingInvitationsRequest, opts ...grpc.CallOption) (*ListOrganizationInvitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrganizationInvitationsResponse)
	err := c.cc.Invoke(ctx, OrganizationInvitationService_GetPendingInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationInvitationServiceClient) CreateInvitation(ctx context.Context, in *CreateInvitationRequest, opts ...grpc.CallOption) (*TenantSuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantSuccessResponse)
	err := c.cc.Invoke(ctx, OrganizationInvitationService_CreateInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationInvitationServiceClient) ListInvitations(ctx context.Context, in *ListInvitationsRequest, opts ...grpc.CallOption) (*ListOrganizationInvitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrganizationInvitationsResponse)
	err := c.cc.Invoke(ctx, OrganizationInvitationService_ListInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationInvitationServiceClient) GetPendingByOrg(ctx context.Context, in *TenantOrganizationIDRequest, opts ...grpc.CallOption) (*ListOrgInvitationsResponseForOrg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrgInvitationsResponseForOrg)
	err := c.cc.Invoke(ctx, OrganizationInvitationService_GetPendingByOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrganizationInvitationServiceServer is the server API for OrganizationInvitationService service.
// All implementations must embed UnimplementedOrganizationInvitationServiceServer
// for forward compatibility.
type OrganizationInvitationServiceServer interface {
	// --- Public / Bypasses Org Check ---
	AcceptInvitation(context.Context, *AcceptInvitationRequest) (*TenantSuccessResponse, error)
	// A user canceling their own pending invite doesn't require org membership yet
	CancelInvitation(context.Context, *CancelInvitationRequest) (*TenantSuccessResponse, error)
	GetPendingInvitations(context.Context, *GetPendingInvitationsRequest) (*ListOrganizationInvitationsResponse, error)
	// --- Requires Org Membership ---
	CreateInvitation(context.Context, *CreateInvitationRequest) (*TenantSuccessResponse, error)
	ListInvitations(context.Context, *ListInvitationsRequest) (*ListOrganizationInvitationsResponse, error)
	GetPendingByOrg(context.Context, *TenantOrganizationIDRequest) (*ListOrgInvitationsResponseForOrg, error)
	mustEmbedUnimplementedOrganizationInvitationServiceServer()
}

// UnimplementedOrganizationInvitationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrganizationInvitationServiceServer struct{}

func (UnimplementedOrganizationInvitationServiceServer) AcceptInvitation(context.Context, *AcceptInvitationRequest) (*TenantSuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptInvitation not implemented")
}
func (UnimplementedOrganizationInvitationServiceServer) CancelInvitation(context.Context, *CancelInvitationRequest) (*TenantSuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelInvitation not implemented")
}
func (UnimplementedOrganizationInvitationServiceServer) GetPendingInvitations(context.Context, *GetPendingInvitationsRequest) (*ListOrganizationInvitationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingInvitations not implemented")
}
func (UnimplementedOrganizationInvitationServiceServer) CreateInvitation(context.Context, *CreateInvitationRequest) (*TenantSuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInvitation not implemented")
}
func (UnimplementedOrganizationInvitationServiceServer) ListInvitations(context.Context, *ListInvitationsRequest) (*ListOrganizationInvitationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInvitations not implemented")
}
func (UnimplementedOrganizationInvitationServiceServer) GetPendingByOrg(context.Context, *TenantOrganizationIDRequest) (*ListOrgInvitationsResponseForOrg, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingByOrg not implemented")
}
func (UnimplementedOrganizationInvitationServiceServer) mustEmbedUnimplementedOrganizationInvitationServiceServer() {
}
func (UnimplementedOrganizationInvitationServiceServer) testEmbeddedByValue() {}

// UnsafeOrganizationInvitationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrganizationInvitationServiceServer will
// result in compilation errors.
type UnsafeOrganizationInvitationServiceServer interface {
	mustEmbedUnimplementedOrganizationInvitationServiceServer()
}

func RegisterOrganizationInvitationServiceServer(s grpc.ServiceRegistrar, srv OrganizationInvitationServiceServer) {
	// If the following call panics, it indicates UnimplementedOrganizationInvitationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrganizationInvitationService_ServiceDesc, srv)
}

func _OrganizationInvitationService_AcceptInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationInvitationServiceServer).AcceptInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationInvitationService_AcceptInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationInvitationServiceServer).AcceptInvitation(ctx, req.(*AcceptInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationInvitationService_CancelInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationInvitationServiceServer).CancelInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationInvitationService_CancelInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationInvitationServiceServer).CancelInvitation(ctx, req.(*CancelInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationInvitationService_GetPendingInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationInvitationServiceServer).GetPendingInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationInvitationService_GetPendingInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationInvitationServiceServer).GetPendingInvitations(ctx, req.(*GetPendingInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationInvitationService_CreateInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationInvitationServiceServer).CreateInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationInvitationService_CreateInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationInvitationServiceServer).CreateInvitation(ctx, req.(*CreateInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationInvitationService_ListInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationInvitationServiceServer).ListInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationInvitationService_ListInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationInvitationServiceServer).ListInvitations(ctx, req.(*ListInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationInvitationService_GetPendingByOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantOrganizationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationInvitationServiceServer).GetPendingByOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrganizationInvitationService_GetPendingByOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationInvitationServiceServer).GetPendingByOrg(ctx, req.(*TenantOrganizationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrganizationInvitationService_ServiceDesc is the grpc.ServiceDesc for OrganizationInvitationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrganizationInvitationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tenant.v1.OrganizationInvitationService",
	HandlerType: (*OrganizationInvitationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcceptInvitation",
			Handler:    _OrganizationInvitationService_AcceptInvitation_Handler,
		},
		{
			MethodName: "CancelInvitation",
			Handler:    _OrganizationInvitationService_CancelInvitation_Handler,
		},
		{
			MethodName: "GetPendingInvitations",
			Handler:    _OrganizationInvitationService_GetPendingInvitations_Handler,
		},
		{
			MethodName: "CreateInvitation",
			Handler:    _OrganizationInvitationService_CreateInvitation_Handler,
		},
		{
			MethodName: "ListInvitations",
			Handler:    _OrganizationInvitationService_ListInvitations_Handler,
		},
		{
			MethodName: "GetPendingByOrg",
			Handler:    _OrganizationInvitationService_GetPendingByOrg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tenant/v1/organization_invitation.proto",
}
