// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tenant/v1/project.proto

package tenantV1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------
// Project CRUD
// --------------------
type CreateProjectRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_tenant_v1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProjectRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListProjectsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_tenant_v1_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{1}
}

func (x *ListProjectsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_tenant_v1_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{2}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type GetProjectRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_tenant_v1_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{3}
}

func (x *GetProjectRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type UpdateProjectRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name           *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description    *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_tenant_v1_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProjectRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdateProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateProjectRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateProjectRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type ArchiveProjectRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ArchiveProjectRequest) Reset() {
	*x = ArchiveProjectRequest{}
	mi := &file_tenant_v1_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveProjectRequest) ProtoMessage() {}

func (x *ArchiveProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveProjectRequest.ProtoReflect.Descriptor instead.
func (*ArchiveProjectRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{5}
}

func (x *ArchiveProjectRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ArchiveProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type RestoreProjectRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RestoreProjectRequest) Reset() {
	*x = RestoreProjectRequest{}
	mi := &file_tenant_v1_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreProjectRequest) ProtoMessage() {}

func (x *RestoreProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreProjectRequest.ProtoReflect.Descriptor instead.
func (*RestoreProjectRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{6}
}

func (x *RestoreProjectRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *RestoreProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type DeleteProjectRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ConfirmName    string                 `protobuf:"bytes,3,opt,name=confirm_name,json=confirmName,proto3" json:"confirm_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_tenant_v1_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProjectRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *DeleteProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteProjectRequest) GetConfirmName() string {
	if x != nil {
		return x.ConfirmName
	}
	return ""
}

type ProjectIdRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProjectIdRequest) Reset() {
	*x = ProjectIdRequest{}
	mi := &file_tenant_v1_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectIdRequest) ProtoMessage() {}

func (x *ProjectIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectIdRequest.ProtoReflect.Descriptor instead.
func (*ProjectIdRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectIdRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ProjectIdRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Members       []*ProjectMember       `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectResponse) Reset() {
	*x = ProjectResponse{}
	mi := &file_tenant_v1_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectResponse) ProtoMessage() {}

func (x *ProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectResponse.ProtoReflect.Descriptor instead.
func (*ProjectResponse) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{9}
}

func (x *ProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *ProjectResponse) GetMembers() []*ProjectMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type Project struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Slug           string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	IsActive       bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	MaxApiKeys     int32                  `protobuf:"varint,8,opt,name=max_api_keys,json=maxApiKeys,proto3" json:"max_api_keys,omitempty"`
	MaxMembers     int32                  `protobuf:"varint,9,opt,name=max_members,json=maxMembers,proto3" json:"max_members,omitempty"`
	MemberCount    int32                  `protobuf:"varint,10,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_tenant_v1_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{10}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Project) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Project) GetMaxApiKeys() int32 {
	if x != nil {
		return x.MaxApiKeys
	}
	return 0
}

func (x *Project) GetMaxMembers() int32 {
	if x != nil {
		return x.MaxMembers
	}
	return 0
}

func (x *Project) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *Project) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// --------------------
// Project Members
// --------------------
type ListProjectMembersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListProjectMembersRequest) Reset() {
	*x = ListProjectMembersRequest{}
	mi := &file_tenant_v1_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectMembersRequest) ProtoMessage() {}

func (x *ListProjectMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectMembersRequest.ProtoReflect.Descriptor instead.
func (*ListProjectMembersRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{11}
}

func (x *ListProjectMembersRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListProjectMembersRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListProjectMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*ProjectMember       `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectMembersResponse) Reset() {
	*x = ListProjectMembersResponse{}
	mi := &file_tenant_v1_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectMembersResponse) ProtoMessage() {}

func (x *ListProjectMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectMembersResponse.ProtoReflect.Descriptor instead.
func (*ListProjectMembersResponse) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{12}
}

func (x *ListProjectMembersResponse) GetMembers() []*ProjectMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type ProjectMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *ProjectMember         `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberResponse) Reset() {
	*x = ProjectMemberResponse{}
	mi := &file_tenant_v1_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberResponse) ProtoMessage() {}

func (x *ProjectMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberResponse.ProtoReflect.Descriptor instead.
func (*ProjectMemberResponse) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{13}
}

func (x *ProjectMemberResponse) GetMember() *ProjectMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type ProjectMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	JoinedAt      string                 `protobuf:"bytes,7,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"` // RFC3339
	RemovedAt     *string                `protobuf:"bytes,8,opt,name=removed_at,json=removedAt,proto3,oneof" json:"removed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMember) Reset() {
	*x = ProjectMember{}
	mi := &file_tenant_v1_project_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMember) ProtoMessage() {}

func (x *ProjectMember) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMember.ProtoReflect.Descriptor instead.
func (*ProjectMember) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{14}
}

func (x *ProjectMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProjectMember) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProjectMember) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *ProjectMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ProjectMember) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ProjectMember) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

func (x *ProjectMember) GetRemovedAt() string {
	if x != nil && x.RemovedAt != nil {
		return *x.RemovedAt
	}
	return ""
}

type AddProjectMemberRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role           string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddProjectMemberRequest) Reset() {
	*x = AddProjectMemberRequest{}
	mi := &file_tenant_v1_project_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProjectMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProjectMemberRequest) ProtoMessage() {}

func (x *AddProjectMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProjectMemberRequest.ProtoReflect.Descriptor instead.
func (*AddProjectMemberRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{15}
}

func (x *AddProjectMemberRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AddProjectMemberRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *AddProjectMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddProjectMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ChangeProjectMemberRoleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	MemberId       string                 `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Role           string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChangeProjectMemberRoleRequest) Reset() {
	*x = ChangeProjectMemberRoleRequest{}
	mi := &file_tenant_v1_project_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeProjectMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeProjectMemberRoleRequest) ProtoMessage() {}

func (x *ChangeProjectMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeProjectMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*ChangeProjectMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{16}
}

func (x *ChangeProjectMemberRoleRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ChangeProjectMemberRoleRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ChangeProjectMemberRoleRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *ChangeProjectMemberRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RemoveProjectMemberRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	MemberId       string                 `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveProjectMemberRequest) Reset() {
	*x = RemoveProjectMemberRequest{}
	mi := &file_tenant_v1_project_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProjectMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProjectMemberRequest) ProtoMessage() {}

func (x *RemoveProjectMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_project_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProjectMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveProjectMemberRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_project_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveProjectMemberRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *RemoveProjectMemberRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *RemoveProjectMemberRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

var File_tenant_v1_project_proto protoreflect.FileDescriptor

const file_tenant_v1_project_proto_rawDesc = "" +
	"\n" +
	"\x17tenant/v1/project.proto\x12\ttenant.v1\x1a\x1bbuf/validate/validate.proto\x1a\x16tenant/v1/common.proto\"\x87\x01\n" +
	"\x14CreateProjectRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x03R\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"G\n" +
	"\x13ListProjectsRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\"F\n" +
	"\x14ListProjectsResponse\x12.\n" +
	"\bprojects\x18\x01 \x03(\v2\x12.tenant.v1.ProjectR\bprojects\"m\n" +
	"\x11GetProjectRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12&\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tprojectId\"\xc9\x01\n" +
	"\x14UpdateProjectRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12&\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tprojectId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"q\n" +
	"\x15ArchiveProjectRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12&\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tprojectId\"q\n" +
	"\x15RestoreProjectRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12&\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tprojectId\"\x9c\x01\n" +
	"\x14DeleteProjectRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12&\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tprojectId\x12*\n" +
	"\fconfirm_name\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vconfirmName\"l\n" +
	"\x10ProjectIdRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12&\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tprojectId\"s\n" +
	"\x0fProjectResponse\x12,\n" +
	"\aproject\x18\x01 \x01(\v2\x12.tenant.v1.ProjectR\aproject\x122\n" +
	"\amembers\x18\x02 \x03(\v2\x18.tenant.v1.ProjectMemberR\amembers\"\xcd\x02\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\x12 \n" +
	"\fmax_api_keys\x18\b \x01(\x05R\n" +
	"maxApiKeys\x12\x1f\n" +
	"\vmax_members\x18\t \x01(\x05R\n" +
	"maxMembers\x12!\n" +
	"\fmember_count\x18\n" +
	" \x01(\x05R\vmemberCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"u\n" +
	"\x19ListProjectMembersRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12&\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tprojectId\"P\n" +
	"\x1aListProjectMembersResponse\x122\n" +
	"\amembers\x18\x01 \x03(\v2\x18.tenant.v1.ProjectMemberR\amembers\"I\n" +
	"\x15ProjectMemberResponse\x120\n" +
	"\x06member\x18\x01 \x01(\v2\x18.tenant.v1.ProjectMemberR\x06member\"\xec\x01\n" +
	"\rProjectMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12\x1b\n" +
	"\tjoined_at\x18\a \x01(\tR\bjoinedAt\x12\"\n" +
	"\n" +
	"removed_at\x18\b \x01(\tH\x00R\tremovedAt\x88\x01\x01B\r\n" +
	"\v_removed_at\"\xa9\x01\n" +
	"\x17AddProjectMemberRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12&\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tprojectId\x12 \n" +
	"\auser_id\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"\xb4\x01\n" +
	"\x1eChangeProjectMemberRoleRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12&\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tprojectId\x12$\n" +
	"\tmember_id\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bmemberId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"\x9c\x01\n" +
	"\x1aRemoveProjectMemberRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12&\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tprojectId\x12$\n" +
	"\tmember_id\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bmemberId2\xd9\b\n" +
	"\x0eProjectService\x12L\n" +
	"\rCreateProject\x12\x1f.tenant.v1.CreateProjectRequest\x1a\x1a.tenant.v1.ProjectResponse\x12O\n" +
	"\fListProjects\x12\x1e.tenant.v1.ListProjectsRequest\x1a\x1f.tenant.v1.ListProjectsResponse\x12F\n" +
	"\n" +
	"GetProject\x12\x1c.tenant.v1.GetProjectRequest\x1a\x1a.tenant.v1.ProjectResponse\x12L\n" +
	"\rUpdateProject\x12\x1f.tenant.v1.UpdateProjectRequest\x1a\x1a.tenant.v1.ProjectResponse\x12T\n" +
	"\x0eArchiveProject\x12 .tenant.v1.ArchiveProjectRequest\x1a .tenant.v1.TenantSuccessResponse\x12T\n" +
	"\x0eRestoreProject\x12 .tenant.v1.RestoreProjectRequest\x1a .tenant.v1.TenantSuccessResponse\x12R\n" +
	"\rDeleteProject\x12\x1f.tenant.v1.DeleteProjectRequest\x1a .tenant.v1.TenantSuccessResponse\x12Z\n" +
	"\vListMembers\x12$.tenant.v1.ListProjectMembersRequest\x1a%.tenant.v1.ListProjectMembersResponse\x12Z\n" +
	"\x10GetCurrentMember\x12$.tenant.v1.ListProjectMembersRequest\x1a .tenant.v1.ProjectMemberResponse\x12Q\n" +
	"\tAddMember\x12\".tenant.v1.AddProjectMemberRequest\x1a .tenant.v1.ProjectMemberResponse\x12_\n" +
	"\x10ChangeMemberRole\x12).tenant.v1.ChangeProjectMemberRoleRequest\x1a .tenant.v1.TenantSuccessResponse\x12W\n" +
	"\fRemoveMember\x12%.tenant.v1.RemoveProjectMemberRequest\x1a .tenant.v1.TenantSuccessResponse\x12M\n" +
	"\fLeaveProject\x12\x1b.tenant.v1.ProjectIdRequest\x1a .tenant.v1.TenantSuccessResponseB7Z5github.com/vyolayer/vyolayer/proto/tenant/v1;tenantV1b\x06proto3"

var (
	file_tenant_v1_project_proto_rawDescOnce sync.Once
	file_tenant_v1_project_proto_rawDescData []byte
)

func file_tenant_v1_project_proto_rawDescGZIP() []byte {
	file_tenant_v1_project_proto_rawDescOnce.Do(func() {
		file_tenant_v1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenant_v1_project_proto_rawDesc), len(file_tenant_v1_project_proto_rawDesc)))
	})
	return file_tenant_v1_project_proto_rawDescData
}

var file_tenant_v1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_tenant_v1_project_proto_goTypes = []any{
	(*CreateProjectRequest)(nil),           // 0: tenant.v1.CreateProjectRequest
	(*ListProjectsRequest)(nil),            // 1: tenant.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),           // 2: tenant.v1.ListProjectsResponse
	(*GetProjectRequest)(nil),              // 3: tenant.v1.GetProjectRequest
	(*UpdateProjectRequest)(nil),           // 4: tenant.v1.UpdateProjectRequest
	(*ArchiveProjectRequest)(nil),          // 5: tenant.v1.ArchiveProjectRequest
	(*RestoreProjectRequest)(nil),          // 6: tenant.v1.RestoreProjectRequest
	(*DeleteProjectRequest)(nil),           // 7: tenant.v1.DeleteProjectRequest
	(*ProjectIdRequest)(nil),               // 8: tenant.v1.ProjectIdRequest
	(*ProjectResponse)(nil),                // 9: tenant.v1.ProjectResponse
	(*Project)(nil),                        // 10: tenant.v1.Project
	(*ListProjectMembersRequest)(nil),      // 11: tenant.v1.ListProjectMembersRequest
	(*ListProjectMembersResponse)(nil),     // 12: tenant.v1.ListProjectMembersResponse
	(*ProjectMemberResponse)(nil),          // 13: tenant.v1.ProjectMemberResponse
	(*ProjectMember)(nil),                  // 14: tenant.v1.ProjectMember
	(*AddProjectMemberRequest)(nil),        // 15: tenant.v1.AddProjectMemberRequest
	(*ChangeProjectMemberRoleRequest)(nil), // 16: tenant.v1.ChangeProjectMemberRoleRequest
	(*RemoveProjectMemberRequest)(nil),     // 17: tenant.v1.RemoveProjectMemberRequest
	(*TenantSuccessResponse)(nil),          // 18: tenant.v1.TenantSuccessResponse
}
var file_tenant_v1_project_proto_depIdxs = []int32{
	10, // 0: tenant.v1.ListProjectsResponse.projects:type_name -> tenant.v1.Project
	10, // 1: tenant.v1.ProjectResponse.project:type_name -> tenant.v1.Project
	14, // 2: tenant.v1.ProjectResponse.members:type_name -> tenant.v1.ProjectMember
	14, // 3: tenant.v1.ListProjectMembersResponse.members:type_name -> tenant.v1.ProjectMember
	14, // 4: tenant.v1.ProjectMemberResponse.member:type_name -> tenant.v1.ProjectMember
	0,  // 5: tenant.v1.ProjectService.CreateProject:input_type -> tenant.v1.CreateProjectRequest
	1,  // 6: tenant.v1.ProjectService.ListProjects:input_type -> tenant.v1.ListProjectsRequest
	3,  // 7: tenant.v1.ProjectService.GetProject:input_type -> tenant.v1.GetProjectRequest
	4,  // 8: tenant.v1.ProjectService.UpdateProject:input_type -> tenant.v1.UpdateProjectRequest
	5,  // 9: tenant.v1.ProjectService.ArchiveProject:input_type -> tenant.v1.ArchiveProjectRequest
	6,  // 10: tenant.v1.ProjectService.RestoreProject:input_type -> tenant.v1.RestoreProjectRequest
	7,  // 11: tenant.v1.ProjectService.DeleteProject:input_type -> tenant.v1.DeleteProjectRequest
	11, // 12: tenant.v1.ProjectService.ListMembers:input_type -> tenant.v1.ListProjectMembersRequest
	11, // 13: tenant.v1.ProjectService.GetCurrentMember:input_type -> tenant.v1.ListProjectMembersRequest
	15, // 14: tenant.v1.ProjectService.AddMember:input_type -> tenant.v1.AddProjectMemberRequest
	16, // 15: tenant.v1.ProjectService.ChangeMemberRole:input_type -> tenant.v1.ChangeProjectMemberRoleRequest
	17, // 16: tenant.v1.ProjectService.RemoveMember:input_type -> tenant.v1.RemoveProjectMemberRequest
	8,  // 17: tenant.v1.ProjectService.LeaveProject:input_type -> tenant.v1.ProjectIdRequest
	9,  // 18: tenant.v1.ProjectService.CreateProject:output_type -> tenant.v1.ProjectResponse
	2,  // 19: tenant.v1.ProjectService.ListProjects:output_type -> tenant.v1.ListProjectsResponse
	9,  // 20: tenant.v1.ProjectService.GetProject:output_type -> tenant.v1.ProjectResponse
	9,  // 21: tenant.v1.ProjectService.UpdateProject:output_type -> tenant.v1.ProjectResponse
	18, // 22: tenant.v1.ProjectService.ArchiveProject:output_type -> tenant.v1.TenantSuccessResponse
	18, // 23: tenant.v1.ProjectService.RestoreProject:output_type -> tenant.v1.TenantSuccessResponse
	18, // 24: tenant.v1.ProjectService.DeleteProject:output_type -> tenant.v1.TenantSuccessResponse
	12, // 25: tenant.v1.ProjectService.ListMembers:output_type -> tenant.v1.ListProjectMembersResponse
	13, // 26: tenant.v1.ProjectService.GetCurrentMember:output_type -> tenant.v1.ProjectMemberResponse
	13, // 27: tenant.v1.ProjectService.AddMember:output_type -> tenant.v1.ProjectMemberResponse
	18, // 28: tenant.v1.ProjectService.ChangeMemberRole:output_type -> tenant.v1.TenantSuccessResponse
	18, // 29: tenant.v1.ProjectService.RemoveMember:output_type -> tenant.v1.TenantSuccessResponse
	18, // 30: tenant.v1.ProjectService.LeaveProject:output_type -> tenant.v1.TenantSuccessResponse
	18, // [18:31] is the sub-list for method output_type
	5,  // [5:18] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_tenant_v1_project_proto_init() }
func file_tenant_v1_project_proto_init() {
	if File_tenant_v1_project_proto != nil {
		return
	}
	file_tenant_v1_common_proto_init()
	file_tenant_v1_project_proto_msgTypes[4].OneofWrappers = []any{}
	file_tenant_v1_project_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_v1_project_proto_rawDesc), len(file_tenant_v1_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenant_v1_project_proto_goTypes,
		DependencyIndexes: file_tenant_v1_project_proto_depIdxs,
		MessageInfos:      file_tenant_v1_project_proto_msgTypes,
	}.Build()
	File_tenant_v1_project_proto = out.File
	file_tenant_v1_project_proto_goTypes = nil
	file_tenant_v1_project_proto_depIdxs = nil
}
