// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: iam/v1/common.proto

package iAMV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IAMSuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IAMSuccessResponse) Reset() {
	*x = IAMSuccessResponse{}
	mi := &file_iam_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IAMSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IAMSuccessResponse) ProtoMessage() {}

func (x *IAMSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IAMSuccessResponse.ProtoReflect.Descriptor instead.
func (*IAMSuccessResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *IAMSuccessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IAMSuccessResponse) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type IAMEmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IAMEmptyRequest) Reset() {
	*x = IAMEmptyRequest{}
	mi := &file_iam_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IAMEmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IAMEmptyRequest) ProtoMessage() {}

func (x *IAMEmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IAMEmptyRequest.ProtoReflect.Descriptor instead.
func (*IAMEmptyRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_common_proto_rawDescGZIP(), []int{1}
}

var File_iam_v1_common_proto protoreflect.FileDescriptor

const file_iam_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x13iam/v1/common.proto\x12\x06iam.v1\x1a\x19google/protobuf/any.proto\"^\n" +
	"\x12IAMSuccessResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12.\n" +
	"\apayload\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\apayload\"\x11\n" +
	"\x0fIAMEmptyRequestB1Z/github.com/vyolayer/vyolayer/proto/iam/v1;iAMV1b\x06proto3"

var (
	file_iam_v1_common_proto_rawDescOnce sync.Once
	file_iam_v1_common_proto_rawDescData []byte
)

func file_iam_v1_common_proto_rawDescGZIP() []byte {
	file_iam_v1_common_proto_rawDescOnce.Do(func() {
		file_iam_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_v1_common_proto_rawDesc), len(file_iam_v1_common_proto_rawDesc)))
	})
	return file_iam_v1_common_proto_rawDescData
}

var file_iam_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_iam_v1_common_proto_goTypes = []any{
	(*IAMSuccessResponse)(nil), // 0: iam.v1.IAMSuccessResponse
	(*IAMEmptyRequest)(nil),    // 1: iam.v1.IAMEmptyRequest
	(*anypb.Any)(nil),          // 2: google.protobuf.Any
}
var file_iam_v1_common_proto_depIdxs = []int32{
	2, // 0: iam.v1.IAMSuccessResponse.payload:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_iam_v1_common_proto_init() }
func file_iam_v1_common_proto_init() {
	if File_iam_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_v1_common_proto_rawDesc), len(file_iam_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iam_v1_common_proto_goTypes,
		DependencyIndexes: file_iam_v1_common_proto_depIdxs,
		MessageInfos:      file_iam_v1_common_proto_msgTypes,
	}.Build()
	File_iam_v1_common_proto = out.File
	file_iam_v1_common_proto_goTypes = nil
	file_iam_v1_common_proto_depIdxs = nil
}
